### ISSUE TITLE
Liked coubs not enough

### ISSUE THREAD

**Issue by uunnxx** [mkevac/coubdl#1]
Hi there!
Can we get also "Bookmarks" from coub ?
 
And I'm getting "file name too long" error, can we check filename length, and if it's too long, change it ?

**Comment by uunnxx** [comment]
If it's possible to get `bookmarks` it would be great to separate them (folder), 'cause `bookmarks` more important than liked coubs.

Thanks.

**Comment by uunnxx** [comment]
Long file names like this one:
https://coub.com/view/2c87sb

**Comment by mkevac** [comment]
I've never used `bookmarks` before, so I went to see if it is possible to do and saw this on https://coub.com/dev/docs/Coub+API%2FOverview:

`Warning. This API is no longer supported and will be disabled on Feb 1, 2021.`

I could not find a "new" API, so seems there will be no API at all :-(

**Comment by uunnxx** [comment]
Thank you anyway, yes, I saw that warning too, so I liked all my bookmarks manually and execute one more time `coubdl`  :D
